-- Structured editorial metadata produced by the AI stage.
-- HTML is always generated by the Worker; these fields are data only.
ALTER TABLE messages ADD COLUMN highlights_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE messages ADD COLUMN confidence REAL;
ALTER TABLE messages ADD COLUMN category TEXT;
ALTER TABLE messages ADD COLUMN ai_processed_at TEXT;

CREATE INDEX IF NOT EXISTS idx_messages_importance
  ON messages (importance DESC, message_date DESC);
CREATE INDEX IF NOT EXISTS idx_messages_category
  ON messages (category);
