/**
 * Phase 4: publishes summarized news to the configured Telegram destination.
 *
 * Guarantees:
 *  - only messages with a real summary, a valid source link and an enabled
 *    source channel are published
 *  - a message is marked published only after Telegram confirms delivery, using
 *    an atomic guarded UPDATE so a repeat run cannot double-publish
 *  - news digests use Telegram's Rich Messages API with RTL HTML; every
 *    AI/source value is escaped before it is inserted, so untrusted content can
 *    never break the markup
 *  - rate limits stop the pass instead of hammering; leftovers retry next hour
 */

import { block, doc, type InputRichMessage } from 'tg-rich-messages';
import { listChannels } from './channels';
import { baleSendMessage, baleSendPhoto } from './bale';
import {
  buildAlbumCaptions,
  MAX_ALBUM_SLIDES,
  MAX_IMAGE_ITEMS,
  renderRunAlbum,
  type BrowserBinding,
  type RenderedSlideImage,
} from './newsImage';
import {
  isValidDestinationChat,
  sendMessage,
  sendRichMessage,
  sendMediaGroup,
  sendPhoto,
  TelegramError,
  TelegramRateLimitError,
  type DestinationChat,
} from './telegram';
import type { Env } from './types';
import { topicPresentation } from './topic';

/**
 * Telegram/API safety bound — NOT a product limit.
 *
 * Workers Free allows 50 subrequests per invocation (see Cloudflare "Limits"), and
 * one hourly invocation spends some of them before publishing even starts:
 * one fetch per enabled source channel for collection, up to
 * `MAX_MESSAGES_PER_RUN` (20) for summarization, and occasionally one for the
 * model list. This module therefore spends whatever is left, rather than a flat
 * number that could push the invocation past the platform limit and get it
 * terminated mid-publish.
 */
export const SUBREQUEST_LIMIT_FREE = 50;
/** Matches the summarizer's own per-run message cap. */
export const SUMMARIZE_RESERVE = 20;
export const MODEL_LIST_RESERVE = 1;
/**
 * The run album's subrequest cost: one Browser Run render per slide plus one
 * `sendMediaGroup` (or `sendPhoto` for a single slide). This constant is the
 * DEFAULT (one slide + send) used when no better estimate exists; the pipeline
 * computes the real slide count from the pending news and passes
 * `slides + 1` explicitly. Reserving them keeps the whole invocation inside
 * the platform limit instead of overrunning it at the end of the run. The
 * best-effort Bale mirror is additional but deliberately not counted.
 */
export const IMAGE_RESERVE = 2;
/** Absolute ceiling, never exceeded regardless of the budget. */
export const MAX_MESSAGES_PER_RUN = 40;

/**
 * Messages this run may send: the platform budget minus what the earlier stages
 * and the run album need, clamped to [1, MAX_MESSAGES_PER_RUN]. Deterministic
 * for a given enabled-channel count and album size. Anything left over is
 * recorded with the explicit `run_limit` category and stays unpublished, so the
 * next run continues with it in the same configured order — nothing is silently
 * dropped.
 */
export function publishMessageBudget(
  enabledChannelCount: number,
  imageReserve: number = IMAGE_RESERVE
): number {
  const available =
    SUBREQUEST_LIMIT_FREE -
    enabledChannelCount -
    SUMMARIZE_RESERVE -
    MODEL_LIST_RESERVE -
    Math.max(0, imageReserve);
  return Math.min(MAX_MESSAGES_PER_RUN, Math.max(1, available));
}

const TELEGRAM_TEXT_LIMIT = 4096;
/** Kept below Telegram's limit so HTML tags and topic details always fit. */
const MAX_SUMMARY_CHARS = 1050;
/** AI headlines are short by contract; this only guards the 4096 limit. */
const MAX_TITLE_CHARS = 180;
const MAX_HIGHLIGHT_CHARS = 120;
const MAX_HIGHLIGHTS = 3;

/** Telegram HTML escaping for AI and RSS text. */
export function escapeTelegramHtml(value: string): string {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Wraps our already-escaped digest HTML in the supplied Rich Messages builder.
 * The raw block is intentional here: this HTML is generated by this module,
 * and all dynamic values were escaped before this point. It lets the library
 * validate the document and add the RTL/skip-entity-detection metadata without
 * double-escaping Telegram tags.
 */
export function toTelegramRichMessage(html: string): InputRichMessage {
  return doc(block(() => html)).validate().toInputRichMessage({
    isRtl: true,
    skipEntityDetection: true,
  });
}

/**
 * Prefer Rich Messages, but keep deployments on an older Bot API functional.
 * A method/route rejection is safe to retry through ordinary HTML `sendMessage`;
 * network, rate-limit, authentication, and content errors are not retried here.
 */
async function sendDigestMessage(opts: {
  token: string;
  chatId: DestinationChat;
  html: string;
  fetchImpl?: typeof fetch;
  baseUrl?: string;
}) {
  try {
    return await sendRichMessage({
      token: opts.token,
      chatId: opts.chatId,
      richMessage: toTelegramRichMessage(opts.html),
      fetchImpl: opts.fetchImpl,
      baseUrl: opts.baseUrl,
    });
  } catch (error) {
    const unsupported =
      error instanceof TelegramError &&
      (error.status === 404 ||
        error.status === 405 ||
        (error.status === 400 && /method|rich.?message|unknown|not found/i.test(error.description)));
    if (!unsupported) throw error;

    return sendMessage({
      token: opts.token,
      chatId: opts.chatId,
      text: opts.html,
      parseMode: 'HTML',
      fetchImpl: opts.fetchImpl,
      baseUrl: opts.baseUrl,
    });
  }
}

/** Only original public-channel post links are ever published. */
const SOURCE_URL_RE = /^https:\/\/t\.me\/[A-Za-z][A-Za-z0-9_]{4,31}\/\d{1,20}$/;

/** Source kind of a channel row, mirroring `channels.source_type`. */
export type SourceType = 'telegram' | 'rss';

/**
 * RSS article link: a well-formed absolute https URL with a real hostname.
 * RSS rows store the article URL (bbc.com, zoomit.ir, …), never a t.me link —
 * without this rule every RSS summary failed publishing forever as
 * `invalid_source_url`, which also emptied the run image and the Bale mirror.
 */
export function isValidArticleUrl(raw: string): boolean {
  if (!raw || raw.length > 2048) return false;
  if (/[\s\u0000-\u001F\u007F]/.test(raw)) return false;
  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return false;
  }
  return url.protocol === 'https:' && url.hostname.includes('.');
}

/** Per-source-type gate deciding whether a stored source link is publishable. */
export function isUsableSourceUrl(item: { sourceUrl: string; sourceType: SourceType }): boolean {
  return item.sourceType === 'rss'
    ? isValidArticleUrl(item.sourceUrl)
    : SOURCE_URL_RE.test(item.sourceUrl);
}

export interface PublishableMessage {
  id: number;
  channelId: number;
  channelUsername: string;
  /** Used only as a display fallback when a username is missing. */
  channelTitle: string | null;
  /** 'telegram' for public channels, 'rss' for feed-backed channels. */
  sourceType: SourceType;
  telegramMessageId: number;
  summaryText: string;
  /** AI headline. NULL for rows summarized before migration 0008. */
  title: string | null;
  /** AI global importance 1-5. NULL until the ranking stage has run. */
  importance: number | null;
  /** AI editorial topic used for the digest emoji and image accent. */
  category?: string | null;
  /** Optional AI key points, stored as JSON and treated as display data only. */
  highlights?: string[];
  messageDate: string;
  sourceUrl: string;
}

export type PublishErrorCategory =
  | 'invalid_source_url'
  | 'rate_limited'
  | 'telegram_error'
  | 'network'
  | 'run_limit';

export interface PublishFailure {
  messageId: number;
  category: PublishErrorCategory;
  retryAfterSeconds?: number;
}

export interface PublishReport {
  eligible: number;
  published: number;
  failures: PublishFailure[];
  rateLimited: boolean;
  destination: string | null;
  /** Absent when no image was attempted. */
  image?: ImagePublishOutcome;
  /** Bale mirror counters; absent when Bale delivery is not configured. */
  bale?: { sent: number; failed: number };
}

export interface PublishOptions {
  token?: string;
  destination?: string;
  fetchImpl?: typeof fetch;
  baseUrl?: string;
  /**
   * Browser Run binding. When absent, the run album is skipped entirely and the
   * per-channel text digests behave exactly as before.
   */
  browser?: BrowserBinding;
  now?: Date;
  /**
   * Wait between two album slide renders, honoring the free-plan Quick Action
   * rate limit (≈1 request/10s). The pipeline passes the production value;
   * 0 (default) renders back to back.
   */
  renderSpacingMs?: number;
  /** Injectable wait, so tests never sleep for real. */
  sleepImpl?: (ms: number) => Promise<void>;
  /**
   * Optional Bale mirror (BALE_BOT_TOKEN + BALE_DESTINATION_CHANNEL). Every
   * delivered Telegram message — the run album and each text digest part — is
   * also sent to Bale. Best effort: a Bale failure is logged and counted but
   * never affects Telegram delivery or publish state.
   */
  bale?: BaleDeliveryOptions;
}

/** Outcome of the optional run album (the multi-image slideshow). */
export interface ImagePublishOutcome {
  /** Slide images actually sent in the album (at most MAX_ALBUM_SLIDES). */
  slides: number;
  /** News items carried across the sent slides (up to four per slide). */
  selected: number;
  /** Distinct source channels represented in the album. */
  channels: number;
  sent: boolean;
  bytes: number;
  width: number;
  height: number;
  browserRunMs: number;
  /** Overflow headlines carried by the last slide's ticker and caption. */
  ticker: number;
  /** Selected slides that failed to render and were skipped. */
  skipped: number;
  /** Set when rendering or sending failed; text publishing is unaffected. */
  error?: string;
  /** Short, safe detail behind `error` (stage/status), for run reports. */
  detail?: string;
}

/**
 * Reads the destination from the server-side environment only. It is never
 * exposed through the API, the frontend, or the database.
 */
export function resolveDestination(env: Env): DestinationChat | null {
  const raw = env.TELEGRAM_DESTINATION_CHANNEL?.trim();
  return raw && isValidDestinationChat(raw) ? (raw as DestinationChat) : null;
}

/** Bale destination: @username or a numeric chat/channel id. */
export function isValidBaleDestination(value: string): boolean {
  return /^@[A-Za-z][A-Za-z0-9_]{2,31}$/.test(value) || /^-?\d{1,20}$/.test(value);
}

/** Credentials for the best-effort Bale mirror of the Telegram output. */
export interface BaleDeliveryOptions {
  token: string;
  destination: string;
}

/**
 * Reads the Bale mirror configuration from the server-side environment only.
 * Returns null when Bale is not configured (either secret missing) or the
 * destination is malformed — in both cases publishing stays Telegram-only.
 */
export function resolveBaleDelivery(env: Env): BaleDeliveryOptions | null {
  const token = env.BALE_BOT_TOKEN?.trim();
  const destination = env.BALE_DESTINATION_CHANNEL?.trim();
  if (!token || !destination) return null;
  if (!isValidBaleDestination(destination)) {
    console.error(
      JSON.stringify({
        event: 'publish',
        operation: 'bale',
        status: 'skipped',
        category: 'bale_destination_invalid',
        timestamp: new Date().toISOString(),
      })
    );
    return null;
  }
  return { token, destination };
}

/**
 * Reads every publishable row, newest-run backlog included.
 *
 * Deliberately uncapped: a per-channel or global row cap would silently
 * postpone valid news from the current window to a later hour. Ordering is by
 * configured channel order, then chronological inside each channel.
 */
export async function selectPublishableMessages(db: D1Database): Promise<PublishableMessage[]> {
  const { results } = await db
    .prepare(
      `SELECT m.id, m.source_channel_id, c.channel_username, c.channel_title, c.source_type, m.telegram_message_id,
              m.summary_text, m.title, m.importance, m.category, m.highlights_json, m.message_date, m.source_url
         FROM messages m
         JOIN channels c ON c.id = m.source_channel_id
        WHERE c.enabled = 1
          AND m.filter_status <> 'filtered'
          AND m.summarized_at IS NOT NULL
          AND m.published_at IS NULL
          AND TRIM(COALESCE(m.summary_text, '')) <> ''
          AND TRIM(COALESCE(m.source_url, '')) <> ''
        ORDER BY m.source_channel_id ASC, m.message_date ASC, m.id ASC`
    )
    .all<{
      id: number;
      source_channel_id: number;
      channel_username: string;
      channel_title: string | null;
      source_type: string | null;
      telegram_message_id: number;
      summary_text: string;
      title: string | null;
      importance: number | null;
      category: string | null;
      highlights_json: string | null;
      message_date: string;
      source_url: string;
    }>();

  return (results ?? []).map((r) => ({
    id: r.id,
    channelId: r.source_channel_id,
    channelUsername: r.channel_username,
    channelTitle: r.channel_title ?? null,
    sourceType: (r.source_type === 'rss' ? 'rss' : 'telegram') as SourceType,
    telegramMessageId: r.telegram_message_id,
    summaryText: r.summary_text,
    title: r.title ?? null,
    importance: r.importance ?? null,
    category: r.category ?? null,
    highlights: parseHighlights(r.highlights_json),
    messageDate: r.message_date,
    sourceUrl: r.source_url,
  }));
}

/** Parses AI key points defensively; malformed legacy data is simply omitted. */
function parseHighlights(raw: string | null): string[] {
  if (!raw) return [];
  try {
    const value: unknown = JSON.parse(raw);
    if (!Array.isArray(value)) return [];
    return value
      .filter((item): item is string => typeof item === 'string')
      .map((item) => item.trim())
      .filter(Boolean)
      .slice(0, MAX_HIGHLIGHTS);
  } catch {
    return [];
  }
}

/** One source channel and its publishable news, oldest first. */
export interface ChannelGroup {
  channelId: number;
  channelUsername: string;
  channelTitle: string | null;
  sourceType: SourceType;
  items: PublishableMessage[];
}

/**
 * Groups rows by source channel, preserving the configured channel order
 * (channel id order) and chronological order inside each group.
 */
export function groupByChannel(items: PublishableMessage[]): ChannelGroup[] {
  const groups = new Map<number, ChannelGroup>();
  for (const item of items) {
    const existing = groups.get(item.channelId);
    if (existing) existing.items.push(item);
    else {
      groups.set(item.channelId, {
        channelId: item.channelId,
        channelUsername: item.channelUsername,
        channelTitle: item.channelTitle ?? null,
        sourceType: item.sourceType ?? 'telegram',
        items: [item],
      });
    }
  }
  return [...groups.values()];
}

export interface DigestPart {
  text: string;
  /** News rows carried by this part; marked published only after delivery. */
  itemIds: number[];
}

/**
 * Display identifier for a channel: its username, else its configured title.
 * RSS channels prefer the configured feed title (e.g. «بی‌بی‌سی فارسی») over the
 * synthetic internal username (`rss_3`).
 * Never invents a name; an empty result makes the digest skip sending.
 */
export function channelDisplayName(item: {
  channelUsername: string;
  channelTitle?: string | null;
  sourceType?: SourceType;
}): string {
  const username = item.channelUsername.trim();
  const title = (item.channelTitle ?? '').trim();
  if (item.sourceType === 'rss') return title || username;
  return username || title;
}

/**
 * Footer/label form of a source name: `@username` for real Telegram usernames,
 * the display title verbatim for everything else (RSS feed names are Persian
 * text and must not get a bogus `@`).
 */
export function sourceLabel(name: string): string {
  return /^[A-Za-z][A-Za-z0-9_]*$/.test(name) ? `@${name}` : name;
}

/**
 * Display form of the configured destination channel.
 *
 * Only used for the footer line that tells readers where the digest is
 * published; the actual `sendMessage` target keeps using the configured value
 * unchanged. Usernames get an `@`, numeric channel ids are printed as stored
 * (no invented handle).
 */
export function destinationLabel(raw: string | undefined): string {
  const value = (raw ?? '').trim();
  if (!value) return '';
  if (value.startsWith('@')) return value;
  if (/^-?\d+$/.test(value)) return value;
  return `@${value}`;
}

/**
 * Builds an HTML-formatted digest for one source channel.
 *
 * Each story deliberately contains both the AI headline and its full summary.
 * The topic emoji comes from the AI category, while every value originating in
 * D1 is escaped before it is sent with Telegram's HTML parse mode.
 *
 * Layout:
 *
 *   🏛️ <b>Headline</b>
 *   📝 <b>خلاصه:</b> The complete detail...
 *   🔎 <b>نکات مهم:</b> point one · point two
 *
 *   📡 <i>منبع: @source</i>
 *   📣 <i>@destination</i>
 */
export function buildChannelDigest(
  channelName: string,
  destination: string,
  items: {
    id: number;
    summaryText: string;
    title?: string | null;
    category?: string | null;
    highlights?: string[];
  }[]
): DigestPart[] {
  const name = channelName.trim();
  if (!name) return [];

  const separator = '\n\n';
  const source = escapeTelegramHtml(sourceLabel(name));
  const displayedDestination = destination.trim() ? escapeTelegramHtml(destination.trim()) : '';
  const footer = `📡 <i>منبع: ${source}</i>${displayedDestination ? `\n📣 <i>${displayedDestination}</i>` : ''}`;
  const overhead = separator.length + footer.length;
  const maxBodyLength = Math.max(1, TELEGRAM_TEXT_LIMIT - overhead);

  const prepared = items
    .map((item) => {
      const summary = sanitizeText(item.summaryText, Math.min(MAX_SUMMARY_CHARS, maxBodyLength));
      const title = item.title
        ? sanitizeText(item.title, MAX_TITLE_CHARS).replace(/\n+/g, ' ').trim()
        : '';
      const highlights = (item.highlights ?? [])
        .map((highlight) => sanitizeText(highlight, MAX_HIGHLIGHT_CHARS).replace(/\n+/g, ' ').trim())
        .filter(Boolean)
        .slice(0, MAX_HIGHLIGHTS);
      const topic = topicPresentation(item.category, `${title} ${summary}`);

      const heading = title
        ? `${topic.emoji} <b>${escapeTelegramHtml(title)}</b>`
        : `${topic.emoji} <b>خبر ${escapeTelegramHtml(topic.label)}</b>`;
      const detail = `📝 <b>خلاصه:</b> ${escapeTelegramHtml(summary)}`;
      const keyPoints = highlights.length > 0
        ? `\n🔎 <b>نکات مهم:</b> ${highlights.map(escapeTelegramHtml).join(' · ')}`
        : '';
      const body = `${heading}\n${detail}${keyPoints}`;
      return { id: item.id, body, summary, title, highlights, topic };
    })
    .filter((item) => item.summary.length > 0 || item.title.length > 0);
  if (prepared.length === 0) return [];

  // A normal AI response is comfortably below the limit. This compact fallback
  // also protects the Bot API limit when legacy data contains a large amount of
  // HTML-sensitive text that expands while escaped.
  for (const item of prepared) {
    if (item.body.length <= maxBodyLength) continue;
    const compactSummary = sanitizeText(item.summary, 600);
    const compactTitle = sanitizeText(item.title, 120).replace(/\n+/g, ' ').trim();
    const topic = item.topic;
    const heading = compactTitle
      ? `${topic.emoji} <b>${escapeTelegramHtml(compactTitle)}</b>`
      : `${topic.emoji} <b>خبر ${escapeTelegramHtml(topic.label)}</b>`;
    item.body = `${heading}\n📝 <b>خلاصه:</b> ${escapeTelegramHtml(compactSummary)}`;
  }

  // Greedy packing on the actual HTML source length. The Bot API measures the
  // resulting message, so conservative accounting of tags keeps every part
  // under 4096 characters even when a digest is split.
  const chunks: { id: number; body: string }[][] = [];
  let current: { id: number; body: string }[] = [];
  let used = overhead;

  for (const item of prepared) {
    const addition = item.body.length + (current.length > 0 ? separator.length : 0);
    if (current.length > 0 && used + addition > TELEGRAM_TEXT_LIMIT) {
      chunks.push(current);
      current = [item];
      used = overhead + item.body.length;
    } else {
      current = [...current, { id: item.id, body: item.body }];
      used += addition;
    }
  }
  if (current.length > 0) chunks.push(current);

  return chunks.map((chunk) => ({
    text: `${chunk.map((item) => item.body).join(separator)}${separator}${footer}`,
    itemIds: chunk.map((item) => item.id),
  }));
}

/** Plain-text sanitizer used before HTML escaping. */
function sanitizeText(text: string, limit: number): string {
  const cleaned = String(text ?? '')
    // Strips C0/C1 control chars except tab and newline.
    .replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/g, '')
    .replace(/\r\n/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();

  return cleaned.length > limit ? `${cleaned.slice(0, Math.max(1, limit - 1)).trimEnd()}…` : cleaned;
}

/**
 * Marks a message published. The `published_at IS NULL` guard makes this
 * idempotent, so a repeated call cannot overwrite or double-count.
 */
export async function markPublished(
  db: D1Database,
  messageId: number,
  destinationMessageId: number
): Promise<boolean> {
  const result = await db
    .prepare(
      `UPDATE messages
          SET published_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now'),
              telegram_destination_message_id = ?1,
              publish_attempts = publish_attempts + 1,
              last_publish_error = NULL
        WHERE id = ?2 AND published_at IS NULL`
    )
    .bind(destinationMessageId, messageId)
    .run();

  return (result.meta.changes ?? 0) > 0;
}

/** Records a safe error category only — never provider bodies or credentials. */
export async function recordPublishFailure(
  db: D1Database,
  messageId: number,
  category: PublishErrorCategory
): Promise<void> {
  await db
    .prepare(
      `UPDATE messages
          SET publish_attempts = publish_attempts + 1,
              last_publish_error = ?1,
              last_publish_error_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
        WHERE id = ?2 AND published_at IS NULL`
    )
    .bind(category, messageId)
    .run();
}

export async function runPublishing(db: D1Database, opts: PublishOptions = {}): Promise<PublishReport> {
  const destination = opts.destination ?? null;

  if (!destination || !isValidDestinationChat(destination)) {
    return {
      eligible: 0,
      published: 0,
      failures: [],
      rateLimited: false,
      destination: null,
    };
  }

  if (!opts.token) {
    console.error(
      JSON.stringify({
        event: 'publish',
        operation: 'skip',
        status: 'skipped',
        category: 'telegram_token_missing',
        timestamp: new Date().toISOString(),
      })
    );
    return { eligible: 0, published: 0, failures: [], rateLimited: false, destination };
  }

  const items = await selectPublishableMessages(db);
  const report: PublishReport = {
    eligible: items.length,
    published: 0,
    failures: [],
    rateLimited: false,
    destination,
  };

  // Best-effort Bale mirror of everything this run delivers to Telegram.
  const bale = opts.bale ?? null;
  const baleCounters = { sent: 0, failed: 0 };
  const finish = (): PublishReport => {
    if (bale) report.bale = { sent: baleCounters.sent, failed: baleCounters.failed };
    return report;
  };

  // Phase 4 guarantee: a row whose stored source link is unusable is never
  // published. The link itself is no longer printed, but the check stands.
  // Telegram rows must carry a t.me post link; RSS rows carry the article URL.
  const usable = items.filter((i) => isUsableSourceUrl(i));
  for (const invalid of items.filter((i) => !isUsableSourceUrl(i))) {
    await recordPublishFailure(db, invalid.id, 'invalid_source_url');
    report.failures.push({ messageId: invalid.id, category: 'invalid_source_url' });
  }

  // One destination message per source channel, in configured channel order.
  // No channel is dropped: every enabled channel is represented.
  const groups = groupByChannel(usable);
  const enabledChannels = (await listChannels(db)).filter((c) => c.enabled).length;

  // The album's real subrequest cost, computed BEFORE anything is sent: one
  // Browser Run render per expected slide plus one sendMediaGroup. Slides are
  // chunked from the same eligibility filter renderRunAlbum uses (AI headline
  // + intro present, importance ≠ 1), so the reserve matches what will really
  // be spent. Without a Browser Run binding or eligible news it is zero.
  const albumEligible = usable.filter(
    (i) => i.summaryText.trim().length > 0 && i.importance !== 1
  );
  const expectedSlides =
    opts.browser && albumEligible.length > 0
      ? Math.min(MAX_ALBUM_SLIDES, Math.ceil(albumEligible.length / MAX_IMAGE_ITEMS))
      : 0;
  const messageBudget = publishMessageBudget(
    enabledChannels,
    expectedSlides > 0 ? expectedSlides + 1 : 0
  );
  let messagesSent = 0;

  // The run album (slideshow). Generated once from the flat publishable list
  // and sent BEFORE any text digest. Deliberately outside the per-channel loop
  // below, so Browser Run is called at most once per slide across the run.
  const image = await publishRunAlbum({
    // RSS rows swap the synthetic `rss_N` username for the feed's display
    // title, so the album slides and captions show «بی‌بی‌سی فارسی», not @rss_3.
    items: usable.map((i) =>
      i.sourceType === 'rss' ? { ...i, channelUsername: channelDisplayName(i) } : i
    ),
    destination,
    token: opts.token,
    browser: opts.browser,
    renderSpacingMs: opts.renderSpacingMs,
    sleepImpl: opts.sleepImpl,
    bale,
    baleCounters,
    fetchImpl: opts.fetchImpl,
    baseUrl: opts.baseUrl,
    now: opts.now,
  });
  // Left absent (not null) when there was nothing to show, so "no image" is
  // distinguishable from "an image that failed".
  if (image) report.image = image;

  for (const group of groups) {
    const parts = buildChannelDigest(
      channelDisplayName(group),
      destinationLabel(destination),
      group.items
    );
    if (parts.length === 0) continue;

    for (const part of parts) {
      if (messagesSent >= messageBudget) {
        // Explicit, deterministic bound. The remainder is recorded (not silently
        // dropped) and stays unpublished, so the next run continues in the same
        // configured order without losing or reordering anything.
        for (const itemId of part.itemIds) {
          await recordPublishFailure(db, itemId, 'run_limit');
          report.failures.push({ messageId: itemId, category: 'run_limit' });
        }
        logPublish('skipped', 'run_limit', group, {
          newsCount: part.itemIds.length,
          messagesSent,
          messageBudget,
        });
        return finish();
      }

      try {
        const sent = await sendDigestMessage({
          token: opts.token!,
          chatId: destination,
          html: part.text,
          fetchImpl: opts.fetchImpl,
          baseUrl: opts.baseUrl,
        });
        messagesSent++;

        // Only the rows carried by THIS delivered message are marked.
        let markedCount = 0;
        for (const itemId of part.itemIds) {
          if (await markPublished(db, itemId, sent.message_id)) markedCount++;
        }
        report.published += markedCount;
        logPublish('ok', undefined, group, {
          destinationMessageId: sent.message_id,
          newsCount: markedCount,
        });

        // Mirror the delivered part to Bale. Only delivered parts are mirrored,
        // so a later retry (rows still unpublished) cannot duplicate on Bale.
        if (bale) {
          try {
            await baleSendMessage({
              token: bale.token,
              chatId: bale.destination,
              text: part.text,
              parseMode: 'HTML',
              fetchImpl: opts.fetchImpl,
            });
            baleCounters.sent++;
          } catch (error) {
            baleCounters.failed++;
            logBale('error', {
              reason: error instanceof Error ? error.message : String(error),
            });
          }
        }
      } catch (error) {
        const category: PublishErrorCategory =
          error instanceof TelegramRateLimitError
            ? 'rate_limited'
            : error instanceof TelegramError && error.status === 0
              ? 'network'
              : 'telegram_error';

        const retryAfter =
          error instanceof TelegramRateLimitError ? error.retryAfterSeconds : undefined;
        for (const itemId of part.itemIds) {
          await recordPublishFailure(db, itemId, category);
          report.failures.push(
            retryAfter === undefined
              ? { messageId: itemId, category }
              : { messageId: itemId, category, retryAfterSeconds: retryAfter }
          );
        }

        if (error instanceof TelegramRateLimitError) {
          // Stop immediately: retrying in a tight loop would burn the invocation
          // budget. Everything left stays unpublished for the next run.
          report.rateLimited = true;
          logPublish('rate_limited', category, group, {
            retryAfterSeconds: error.retryAfterSeconds,
          });
          return finish();
        }

        logPublish('error', category, group, { newsCount: part.itemIds.length });
      }
    }
  }

  return finish();
}

/**
 * Generates and sends THE run album: a slideshow of fixed-template slides,
 * every slide covering four news items (headline + introductory text),
 * delivered by Telegram as a single `sendMediaGroup`.
 *
 * Invariants:
 *  - called exactly once from `runPublishing`, outside the channel loop, so
 *    Browser Run is spent only on the album (≤ MAX_ALBUM_SLIDES renders);
 *  - never touches publish state: a failure here leaves every text digest and
 *    every `published_at` exactly as the existing logic would have left them;
 *  - every PNG is a local buffer released as soon as the send resolves.
 *
 * Returns null when there is nothing to show, in which case no Browser Run
 * request is made at all.
 */
async function publishRunAlbum(input: {
  items: PublishableMessage[];
  destination: string;
  token: string;
  browser: BrowserBinding | undefined;
  renderSpacingMs?: number;
  sleepImpl?: (ms: number) => Promise<void>;
  bale: BaleDeliveryOptions | null;
  baleCounters: { sent: number; failed: number };
  fetchImpl?: typeof fetch;
  baseUrl?: string;
  now?: Date;
}): Promise<ImagePublishOutcome | null> {
  const { items, destination, token, browser } = input;
  if (items.length === 0) return null;

  let album: Awaited<ReturnType<typeof renderRunAlbum>>;
  try {
    album = await renderRunAlbum({
      browser,
      items,
      now: input.now,
      spacingMs: input.renderSpacingMs,
      sleepImpl: input.sleepImpl,
    });
  } catch (error) {
    // Rendering failed before any slide existed (binding unusable). Text
    // publishing continues untouched and nothing is marked published.
    const detail = error instanceof Error ? `${error.name}: ${error.message}`.slice(0, 120) : 'unknown';
    logImage('error', { newsCount: items.length, reason: detail });
    return {
      slides: 0,
      selected: 0,
      channels: 0,
      sent: false,
      bytes: 0,
      width: 0,
      height: 0,
      browserRunMs: 0,
      ticker: 0,
      skipped: 0,
      error: 'render_failed',
      detail,
    };
  }

  // No publishable news, or no Browser Run binding configured: no album and
  // no Browser Run request at all.
  if (!album) return null;

  // Every selected slide failed to render (Browser Run down or rate limited).
  if (album.slides.length === 0) {
    logImage('error', { newsCount: items.length, reason: album.error, skipped: album.skipped });
    return {
      slides: 0,
      selected: 0,
      channels: 0,
      sent: false,
      bytes: 0,
      width: 0,
      height: 0,
      browserRunMs: album.browserRunMs,
      ticker: 0,
      skipped: album.skipped,
      error: 'render_failed',
      ...(album.error ? { detail: album.error } : {}),
    };
  }

  const captions = buildAlbumCaptions(
    album.slides.map((slide) => slide.items),
    album.ticker,
    album.hidden,
    input.now ?? new Date()
  );

  // Mirror every slide to Bale before the Telegram send. Independent and
  // isolated: a Bale failure never changes the Telegram outcome below.
  if (input.bale) {
    for (const [index, slide] of album.slides.entries()) {
      try {
        await baleSendPhoto({
          token: input.bale.token,
          chatId: input.bale.destination,
          photo: slide.png,
          caption: captions[index],
          fetchImpl: input.fetchImpl,
        });
        input.baleCounters.sent++;
      } catch (error) {
        input.baleCounters.failed++;
        logBale('error', {
          reason: error instanceof Error ? error.message : String(error),
        });
      }
    }
  }

  const base: ImagePublishOutcome = {
    slides: album.slides.length,
    selected: album.selected,
    channels: new Set(album.slides.flatMap((slide) => slide.items.map((i) => i.channelUsername)))
      .size,
    sent: false,
    bytes: album.slides.reduce((sum, slide) => sum + slide.bytes, 0),
    width: album.slides[0].width,
    height: album.slides[0].height,
    browserRunMs: album.browserRunMs,
    ticker: album.ticker.filter((t) => !t.more).length,
    skipped: album.skipped,
  };

  try {
    await sendAlbum({
      token,
      destination,
      slides: album.slides,
      captions,
      fetchImpl: input.fetchImpl,
      baseUrl: input.baseUrl,
    });
    // The PNGs are never persisted; they stay referenced only by the local
    // album variable and become unreachable when this function returns.
    logImage('ok', { ...base, newsCount: items.length });
    return { ...base, sent: true };
  } catch (error) {
    const detail =
      error instanceof TelegramRateLimitError
        ? 'rate_limited'
        : error instanceof TelegramError
          ? `HTTP ${error.status}`
          : 'network';
    logImage('send_failed', {
      newsCount: items.length,
      reason: error instanceof Error ? error.message : String(error),
    });
    return { ...base, error: 'send_failed', detail };
  }
}

/**
 * Sends the album: one `sendMediaGroup` for two or more slides — Telegram
 * shows them as a swipeable slideshow — and a plain `sendPhoto` for a single
 * slide, because a media group requires at least two items.
 */
async function sendAlbum(input: {
  token: string;
  destination: string;
  slides: RenderedSlideImage[];
  captions: string[];
  fetchImpl?: typeof fetch;
  baseUrl?: string;
}): Promise<void> {
  if (input.slides.length === 1) {
    await sendPhoto({
      token: input.token,
      chatId: input.destination,
      photo: input.slides[0].png,
      caption: input.captions[0],
      fetchImpl: input.fetchImpl,
      baseUrl: input.baseUrl,
    });
    return;
  }
  await sendMediaGroup({
    token: input.token,
    chatId: input.destination,
    media: input.slides.map((slide, index) => ({
      photo: slide.png,
      caption: input.captions[index],
    })),
    fetchImpl: input.fetchImpl,
    baseUrl: input.baseUrl,
  });
}

function logImage(status: string, extra: Record<string, unknown> = {}): void {
  console.log(
    JSON.stringify({
      event: 'publish',
      operation: 'runImage',
      status,
      timestamp: new Date().toISOString(),
      ...extra,
    })
  );
}

/** Best-effort Bale mirror bookkeeping; reasons are error messages only. */
function logBale(status: string, extra: Record<string, unknown> = {}): void {
  console.log(
    JSON.stringify({
      event: 'publish',
      operation: 'bale',
      status,
      timestamp: new Date().toISOString(),
      ...extra,
    })
  );
}

function logPublish(
  status: string,
  category: string | undefined,
  group: { channelId: number; channelUsername: string },
  extra: Record<string, unknown> = {}
): void {
  console.log(
    JSON.stringify({
      event: 'publish',
      operation: 'sendMessage',
      status,
      category,
      channel: group.channelUsername,
      channelId: group.channelId,
      timestamp: new Date().toISOString(),
      ...extra,
    })
  );
}
